language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

git:
  depth: 3

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--prefer-stable"

  allow_failures:
    - php: nightly

install:
  - travis_retry composer update --no-interaction --prefer-source ${COMPOSER_FLAGS}

script:
  - composer test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
